### ISSUE TITLE
Problems with naked TLD

### ISSUE THREAD

**Issue by RobinJadoul** [be-oi/beoi.be-oi.be#55]
- The map with the regional centers doesn't show up on `http://be-oi.be`, only on `http://www.be-oi.be`
- HTTPS doesn't work for `http://be-oi.be` because the wildcard `*.be-oi.be` doesn't catch that

**Comment by smadbe** [comment]
certificate problem fixed. nice one

**Comment by smadbe** [comment]
maps fixed
